/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as pagesNot_found_pageRouteImport } from './routes/(pages)/not_found_page'
import { Route as pagesAuthRole_selectionRouteImport } from './routes/(pages)/auth/role_selection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesNot_found_pageRoute = pagesNot_found_pageRouteImport.update({
  id: '/(pages)/not_found_page',
  path: '/not_found_page',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAuthRole_selectionRoute = pagesAuthRole_selectionRouteImport.update({
  id: '/(pages)/auth/role_selection',
  path: '/auth/role_selection',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not_found_page': typeof pagesNot_found_pageRoute
  '/auth/role_selection': typeof pagesAuthRole_selectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not_found_page': typeof pagesNot_found_pageRoute
  '/auth/role_selection': typeof pagesAuthRole_selectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(pages)/not_found_page': typeof pagesNot_found_pageRoute
  '/(pages)/auth/role_selection': typeof pagesAuthRole_selectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/not_found_page' | '/auth/role_selection'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/not_found_page' | '/auth/role_selection'
  id:
    | '__root__'
    | '/'
    | '/(pages)/not_found_page'
    | '/(pages)/auth/role_selection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  pagesNot_found_pageRoute: typeof pagesNot_found_pageRoute
  pagesAuthRole_selectionRoute: typeof pagesAuthRole_selectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/not_found_page': {
      id: '/(pages)/not_found_page'
      path: '/not_found_page'
      fullPath: '/not_found_page'
      preLoaderRoute: typeof pagesNot_found_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/auth/role_selection': {
      id: '/(pages)/auth/role_selection'
      path: '/auth/role_selection'
      fullPath: '/auth/role_selection'
      preLoaderRoute: typeof pagesAuthRole_selectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  pagesNot_found_pageRoute: pagesNot_found_pageRoute,
  pagesAuthRole_selectionRoute: pagesAuthRole_selectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
